version: 2.0

workflows:
  ios:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    scripts:
      - name: Install dependencies
        script: |
          brew install swiftlint
      - name: Build and test
        script: |
          xcodebuild -project YourApp.xcodeproj -scheme YourApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' build test
    artifacts:
      - build/*.ipa
