workflows:
  ios:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_pro
    scripts:
      - name: Install dependencies
        script: |
          brew install swiftlint
      - name: Build and test
        script: |
          xcodebuild -workspace YourApp.xcworkspace -scheme YourApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' build test
